Implement support for KotlinX Serialization
apple/pkl pull request #196
Opened 2024-02-18 22:30 UTC by sgammon

This change adds support for a new code-gen argument, `implementKSerializable`, which results in the annotation `kotlinx.serialization.Serializable` being added to `data` classes during codegen.

New discussion opened [here](apple/pkl#186)

## Approach

A new argument has been added to the Kotlin code generator and Gradle plugin, at `implementKSerializable`. When set to `true`, the code generator annotates data classes with `@kotlinx.serialization.Serializable`.

If both JVM serialization and KotlinX serialization are enabled, the code generator properly qualifies with `java.io.Serializable` and `import kotlinx.serialization.Serializable`. The two are optional and usable independent of each other.

For the moment, this is filed on top of these other PRs to avoid conflicts, since they all touch the code generator; these can be rebased away, though:

- #194 
- #192

### Transitive dependency needs

Users of this code will need to include the KotlinX Serialization compiler plugin in their build, with:
```kotlin
plugins {
  kotlin("plugin.serialization")

  // -- or --
  alias(libs.plugins.kotlin.serialization)  // version catalog

  // -- or --
  id(libs.plugins.kotlin.serialization.get().pluginId)  // multi-module build with version catalog
}
```

And a dependency on KotlinX Serialization Core, for the annotation, at version `1.5.0` or greater:
```kotlin
dependencies {
  api("org.jetbrains.kotlinx:kotlinx-serialization-core:1.5.0")

  // -- or --
  api(libs.kotlinx.serialization.core)
}
```
```toml
[versions]
# ...
kotlinx-serialization = "1.5.0"  # or greater for newer Kotlin metadata versions
# ...

[libraries]
# ...
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
# ...
```

I stopped short of adding an `api` dependency to Pkl's Kotlin runtime library to avoid adding it to consumer dependency graphs downstream. This could easily be added, though, if preferable. Gradle will generally select the newest available version in a user's build, but builds that don't include KotlinX Serialization already will have to download it if it is added this way, of course.

IDEA and Kotlin warn appropriately if the compiler is not included.

### Changelog

- feat(codegen): add support for kotlin `Serializable` annotation
- feat(gradle): add `implementKSerializable` argument
- test(codegen): add test for KotlinX serialization support
- test(codegen): add test for both Java and KotlinX serialization
- test(gradle): add test for compiling with KotlinX serialization
- chore: update lockfiles

2024-02-29 01:18 UTC, bioball requested changes
Can you rebase your changes on top of main? It's a little hard to review at the moment.

One general comment here is that we shouldn't need to actually depend on kotlinx.serialization; we can reference the class by string.

Also another note: Our codegen includes types that aren't `Serializable`. This includes `org.pkl.core.DataSize`, `org.pkl.core.Duration`, and other subclasses of `org.pkl.core.Value`.

Maybe those properties should be marked `@Contextual`, if using kotlinx serialization? And we would leave it to end users to decide how these should be serialized.

2024-02-29 01:18 UTC, bioball commented on pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt
> +        // language=text
```suggestion
```

2024-02-29 01:18 UTC, bioball commented on pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt
> +    val spec = AnnotationSpec.builder(Serializable::class).build()
We can avoid adding a dependency on kotlinx serialization by referencing kotlinx serialization by string:

```suggestion
    val spec = AnnotationSpec
      .builder(ClassName("kotlinx.serialization", "Serializable"))
      .build()
```

2024-03-20 22:22 UTC, sgammon commented
Hey @bioball, sorry I missed your review here! I'll take a look. The problem with sealed classes is a bigger issue that may need some design attention before this feature ships.

2024-08-24 19:11 UTC, vivasmauri1 approved these changes

2024-08-24 19:11 UTC, vivasmauri1 approved these changes

2024-08-24 19:12 UTC, vivasmauri1 commented on pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt
> +  val implementKSerializable: Boolean = false,
okm..

2025-01-28 22:08 UTC, closed without merging

2025-01-28 22:08 UTC, sgammon commented
Closing for now, may rebase later