Enable caching of native image building and test tasks
apple/pkl pull request #409
Opened 2024-04-08 13:29 UTC by stefanobaghino

The native image building task and a few test tasks cannot be cached effectively by Gradle.
1. the native image building is a generic `Exec` tasks for which caching needs to be enabled explicitly (see [docs](https://docs.gradle.org/current/userguide/build_cache.html#using_the_runtime_api)) as the build tool doesn't have natively have enough information to cache it effectively -- furthermore some steps need to be taken to normalize the classpath (JARs come with an embedded timestamp in their manifest and this needs to be ignored), as well as not rely on absolute paths
2. while tests are usually cacheable, path relativity needs to be added as a property to ensure the results can be retrieved from a cache without relying on the environment of the machine running the task

All touched properties got a name to make sure it was easy to find them with [Build Scan®](https://scans.gradle.com/).

These issues have been diagnosed using [the build validation scripts by Gradle](https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/bf70ec7e5e57ab0996d68a970745512b79462134/Gradle.md).

2024-04-08 14:21 UTC, holzensp reviewed
LGTM; wanting a second pair of eyes; @bioball 

No idea why CircleCI errored out on approval, but appears stuck for me.

2024-04-09 07:27 UTC, ribafish approved these changes

2024-04-10 13:57 UTC, stefanobaghino commented
@holzensp Thanks for taking the time to review, I'll wait for @bioball's second look. 🙇🏻

2024-04-15 07:03 UTC, stefanobaghino commented
👋🏻 Hi @bioball! Can this tiny PR get your attention in the coming days? 🙂

2024-04-16 21:22 UTC, bioball requested changes

2024-04-16 21:22 UTC, bioball commented on pkl-cli/pkl-cli.gradle.kts
> +  inputs.files(configurations.runtimeClasspath).withPropertyName("runtimeClasspath").withNormalizer(ClasspathNormalizer::class)
We should provide `bin/native-image` as an input here as well, right?

```suggestion
  inputs.files(configurations.runtimeClasspath).withPropertyName("runtimeClasspath").withNormalizer(ClasspathNormalizer::class)
inputs.files(file(buildInfo.graalVm.baseDir).resolve("bin/native-image")).withPropertyName("graalVmNativeImage").withPathSensitivity(PathSensitivity.ABSOLUTE)
```

2024-04-18 15:28 UTC, merged

2024-04-18 18:59 UTC, stefanobaghino commented
Thank you for taking the time to review! 🙂