Fix the sequence length in the YAML parser
apple/pkl pull request #413
Opened 2024-04-09 09:16 UTC by luuvish

The initialSize in EconomicsMaps.create() is not the actual stored size, hence the accurate size is not determined until ObjectMembers are added after addMembers() called.

Since the size set during the creation of VmListing cannot be changed afterwards, the size of node.getValue() is used instead of members' size.

2024-04-09 13:32 UTC, holzensp requested changes
The test `pkl-core/src/test/files/LanguageSnippetTests/input/api/yamlParser3.pkl` fails with this change. Run `gw build` to reproduce.

2024-04-10 06:32 UTC, luuvish commented
in yamlParser3.pkl,

```yaml
product:
    - sku: BL3940
      quantify: 4
      description: Basketball
      price: 450.00 
    - sku: BL4438H
      quantify: 1
      description: Super Hoop
      price: 2392.00
```
it's result is
```yaml
product {
    "other"
    new {
      sku = "BL4438H"
      quantify = 1
      description = "Super Hoop"
      price = "2392.00"
    }
}
```

but, correct result is
```yaml
product {
    new {
      sku = "BL3940"
      quantify = 4
      description = "Basketball"
      price = 450.00
    }
    new {
      sku = "BL4438H"
      quantify = 1
      description = "Super Hoop"
      price = "2392.00"
    }
    "other"
}
```

The length of the sequence was incorrectly set to 0, causing "other" to be inserted at index 0 and overwriting the contents of index 0.

2024-04-10 12:53 UTC, holzensp commented
I meant the file describing the expected result (`pkl-core/src/test/files/LanguageSnippetTests/output/api/yamlParser3.pcf`) was not updated yet. I've done that for you now.

Btw, totally skipped over saying "nice catch," but it is, so... nice catch! ;)

2024-04-10 13:02 UTC, holzensp approved these changes

2024-04-10 13:02 UTC, merged