Cyclical dependencies report
apple/pkl pull request #731
Opened 2024-10-23 20:03 UTC by stackoverflow

This is based on @bioball's import graph PR.

2024-10-23 23:58 UTC, bioball requested changes
We should use the in-language Java API for this; see `org.pkl.core.Analyzer` for details. The will return an `ImportGraph`, which can be traversed to show cycles; no guessing needed.

I played around with this, and came up with this:

```diff
diff --git a/pkl-core/src/main/java/org/pkl/core/project/Project.java b/pkl-core/src/main/java/org/pkl/core/project/Project.java
index c879335a0..f3d75621b 100644
--- a/pkl-core/src/main/java/org/pkl/core/project/Project.java
+++ b/pkl-core/src/main/java/org/pkl/core/project/Project.java
@@ -19,6 +19,7 @@ import java.net.URI;
 import java.net.URISyntaxException;
 import java.nio.file.FileSystemNotFoundException;
 import java.nio.file.Path;
+import java.util.ArrayList;
 import java.util.HashMap;
 import java.util.List;
 import java.util.Map;
@@ -26,10 +27,12 @@ import java.util.Objects;
 import java.util.function.Function;
 import java.util.regex.Pattern;
 import java.util.stream.Collectors;
+import org.pkl.core.Analyzer;
 import org.pkl.core.Composite;
 import org.pkl.core.Duration;
 import org.pkl.core.Evaluator;
 import org.pkl.core.EvaluatorBuilder;
+import org.pkl.core.ImportGraph;
 import org.pkl.core.ModuleSource;
 import org.pkl.core.PClassInfo;
 import org.pkl.core.PNull;
@@ -49,6 +52,7 @@ import org.pkl.core.packages.PackageLoadError;
 import org.pkl.core.packages.PackageUri;
 import org.pkl.core.packages.PackageUtils;
 import org.pkl.core.resource.ResourceReaders;
+import org.pkl.core.util.ErrorMessages;
 import org.pkl.core.util.IoUtils;
 import org.pkl.core.util.Nullable;
 
@@ -108,16 +112,7 @@ public final class Project {
 
   /** Loads a project from the given source. */
   public static Project load(ModuleSource moduleSource) {
-    try (var evaluator =
-        EvaluatorBuilder.unconfigured()
-            .setSecurityManager(SecurityManagers.defaultManager)
-            .setStackFrameTransformer(StackFrameTransformers.defaultTransformer)
-            .addModuleKeyFactory(ModuleKeyFactories.standardLibrary)
-            .addModuleKeyFactory(ModuleKeyFactories.file)
-            .addModuleKeyFactory(ModuleKeyFactories.classPath(Project.class.getClassLoader()))
-            .addResourceReader(ResourceReaders.environmentVariable())
-            .addResourceReader(ResourceReaders.file())
-            .build()) {
+    try (var evaluator = evaluatorBuilder().build()) {
       return load(evaluator, moduleSource);
     }
   }
@@ -127,15 +122,80 @@ public final class Project {
       var output = evaluator.evaluateOutputValueAs(moduleSource, PClassInfo.Project);
       return Project.parseProject(output);
     } catch (StackOverflowError e) {
-      // this is most probably a cycle between dependencies
-      var cycleChecker = new DependencyCycleChecker(moduleSource);
-      cycleChecker.checkCycles();
+      var cycle = findImportCycle(moduleSource);
+      if (cycle != null) {
+        throw new PklException(ErrorMessages.create("dependencyCycle", renderCycle(cycle)));
+      }
       throw e;
     } catch (URISyntaxException e) {
       throw new PklException(e.getMessage(), e);
     }
   }
 
+  private static String renderCycle(List<URI> cycle) {
+    var sb = new StringBuilder();
+    sb.append("┌─>");
+    var isFirst = true;
+    for (URI uri : cycle) {
+      if (isFirst) {
+        isFirst = false;
+      } else {
+        sb.append("\n│");
+      }
+      sb.append("\n│  ");
+      sb.append(uri.toString());
+    }
+    sb.append("\n└─ ");
+    return sb.toString();
+  }
+
+  private static @Nullable List<URI> findImportCycle(ModuleSource moduleSource) {
+    var builder = evaluatorBuilder();
+    var analyzer =
+        new Analyzer(
+            StackFrameTransformers.defaultTransformer,
+            SecurityManagers.defaultManager,
+            builder.getModuleKeyFactories(),
+            builder.getModuleCacheDir(),
+            builder.getProjectDependencies(),
+            builder.getHttpClient());
+    var graph = analyzer.importGraph(moduleSource.getUri());
+    return doFindCycle(
+        moduleSource.getUri().normalize(),
+        graph,
+        new ArrayList<>(List.of(moduleSource.getUri().normalize())));
+  }
+
+  private static @Nullable List<URI> doFindCycle(
+      URI currentUri, ImportGraph importGraph, List<URI> path) {
+    var imports = importGraph.imports().get(currentUri);
+    var startingUri = path.get(0);
+    for (var imprt : imports) {
+      var uri = imprt.uri();
+      if (uri.equals(startingUri)) {
+        return path;
+      }
+      path.add(uri);
+      var cycle = doFindCycle(uri, importGraph, path);
+      if (cycle != null) {
+        return cycle;
+      }
+      path.remove(path.size() - 1);
+    }
+    return null;
+  }
+
+  private static EvaluatorBuilder evaluatorBuilder() {
+    return EvaluatorBuilder.unconfigured()
+        .setSecurityManager(SecurityManagers.defaultManager)
+        .setStackFrameTransformer(StackFrameTransformers.defaultTransformer)
+        .addModuleKeyFactory(ModuleKeyFactories.standardLibrary)
+        .addModuleKeyFactory(ModuleKeyFactories.file)
+        .addModuleKeyFactory(ModuleKeyFactories.classPath(Project.class.getClassLoader()))
+        .addResourceReader(ResourceReaders.environmentVariable())
+        .addResourceReader(ResourceReaders.file());
+  }
+
   private static DeclaredDependencies parseDependencies(
       PObject module, URI projectFileUri, @Nullable PackageUri packageUri)
       throws URISyntaxException {
diff --git a/pkl-core/src/main/resources/org/pkl/core/errorMessages.properties b/pkl-core/src/main/resources/org/pkl/core/errorMessages.properties
index cca89818b..726619d1f 100644
--- a/pkl-core/src/main/resources/org/pkl/core/errorMessages.properties
+++ b/pkl-core/src/main/resources/org/pkl/core/errorMessages.properties
@@ -825,8 +825,9 @@ stackOverflow=\
 A stack overflow occurred.
 
 dependencyCycle=\
-A stack overflow occurred.\n\
-This is most probably a cycle between dependencies:\n\
+Local project dependencies cannot be circular.\n\
+\n\
+Cycle:\n\
 {0}
 
 multipleUnionDefaults=\
```

This is just what I came up with, but feel free to adjust things.

2024-10-24 00:00 UTC, bioball commented on pkl-core/src/test/kotlin/org/pkl/core/project/ProjectDependenciesResolverTest.kt
> +  }
[nit] move this test to `org.pkl.core.project.ProjectTest`

2024-10-24 09:33 UTC, stackoverflow commented
> This is just what I came up with, but feel free to adjust things.

Adjusted your function to work on cases like: `Project1 -> Project2 -> Project3 -> Project2`.
Also fixed a stack overflow in case the cycle was not coming back to the start URI.

2024-10-24 17:17 UTC, stackoverflow commented on pkl-core/src/main/java/org/pkl/core/project/Project.java
> +        res.add(new TreeSet<>(cycle));
Had to use a `Set` here because otherwise we'd report on every permutation of a cycle.

2024-10-24 23:02 UTC, bioball approved these changes

2024-10-24 23:45 UTC, merged